import img from "../images/room.png";
export const fakeDataWithDetails = [
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 2,
    condition: "furnished",
    id: 1,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    id: 2,
    toilet: 3,
    condition: "Non furnished",
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1520",
    bed: "5",
    sofa: "3",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 7,
    condition: "Refurnished",
    id: 3,
    name: "5 Bedroom flat in Hackney Bridge",
    price: "14270",
    bed: "5",
    sofa: "6",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 22/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 3,
    condition: "Ya furnished",
    id: 4,
    name: "6 Bedroom flat in Hackney Bridge",
    price: "1620",
    bed: "6",
    sofa: "3",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 4,
    condition: "Non furnished",
    id: 5,
    name: "6 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "6",
    sofa: "4",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 30/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 2,
    condition: "furnished",
    id: 6,
    name: "12 Bedroom flat in Hackney Bridge",
    price: "12420",
    bed: "6",
    sofa: "2",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 2,
    condition: "furnished",
    id: 7,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1220",
    bed: "8",
    sofa: "9",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 2,
    condition: "furnished",
    id: 8,
    name: "7 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "7",
    sofa: "5",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 2,
    condition: "furnished",
    id: 9,
    name: "2 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "2",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 2,
    condition: "furnished",
    id: 10,
    name: "6 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "6",
    sofa: "3",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 2,
    condition: "furnished",
    id: 11,
    name: "7 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "7",
    sofa: "4",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    toilet: 2,
    condition: "furnished",
    id: 12,
    name: "7 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "6",
    sofa: "7",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    id: 13,
    toilet: 2,
    condition: "furnished",
    name: "4 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "4",
    sofa: "7",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    detail:
      "ntrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtab",
    id: 14,
    toilet: 2,
    condition: "furnished",
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1720",
    bed: "3",
    sofa: "2",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
];
