import img from "../images/room.png";

export const fakeData = [
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
];
