import img from "../images/room.png";

export const fakeData = [
  {
    image: img,
    id: 1,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "3",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 2,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1520",
    bed: "5",
    sofa: "3",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 3,
    name: "5 Bedroom flat in Hackney Bridge",
    price: "14270",
    bed: "5",
    sofa: "6",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 22/4/25",
  },
  {
    image: img,
    id: 4,
    name: "6 Bedroom flat in Hackney Bridge",
    price: "1620",
    bed: "6",
    sofa: "3",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 5,
    name: "6 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "6",
    sofa: "4",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 30/4/25",
  },
  {
    image: img,
    id: 6,
    name: "12 Bedroom flat in Hackney Bridge",
    price: "12420",
    bed: "6",
    sofa: "2",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 7,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1220",
    bed: "8",
    sofa: "9",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 8,
    name: "7 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "7",
    sofa: "5",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 9,
    name: "2 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "2",
    sofa: "1",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 10,
    name: "6 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "6",
    sofa: "3",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 11,
    name: "7 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "7",
    sofa: "4",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 12,
    name: "7 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "6",
    sofa: "7",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 13,
    name: "4 Bedroom flat in Hackney Bridge",
    price: "1420",
    bed: "4",
    sofa: "7",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
  {
    image: img,
    id: 14,
    name: "3 Bedroom flat in Hackney Bridge",
    price: "1720",
    bed: "3",
    sofa: "2",
    position: "South Kensington (0.1 mile)",
    comment: "Move in form 20/4/25",
  },
];
